export const UserRoles = {
  USER: "USER",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  AGENCY: "AGENCY",
  SUPPORT: "SUPPORT",
};

export const listingTransactionTypeOptions = ["sale", "rent"];
export const listingCategoryOptions = [
  "residential",
  "commercial",
  "land",
  "other",
];
type ListingCategory = (typeof listingCategoryOptions)[number];

export const listingTypeOptions: Record<ListingCategory, string[]> = {
  residential: ["apartment", "house", "vacation house", "other"],
  commercial: [
    "office",
    "store",
    "warehouse",
    "industrial space",
    "other",
  ],
  land: ["construction", "agricultural", "other"],
  other: [
    "garage",
    "business",
    "assembly facilities", // montazni objekti
    "other",
  ],
};

// ------------------------------------------------------------
// opstini vo Makedonija
const manucipalitiesMkd = [
  "Аеродром",
  "Арачиново",
  "Берово",
  "Битола",
  "Богданци",
  "Боговиње",
  "Босилово",
  "Брвеница",
  "Бутел",
  "Валандово",
  "Василево",
  "Вевчани",
  "Велес",
  "Виница",
  "Врапчиште",
  "Гази Баба",
  "Гевгелија",
  "Ѓорче Петров",
  "Гостивар",
  "Градско",
  "Дебар",
  "Дебарца",
  "Делчево",
  "Демир Капија",
  "Демир Хисар",
  "Дојране",
  "Долнени",
  "Желино",
  "Зелениково",
  "Зрновци",
  "Илинден",
  "Јегуновце",
  "Кавадарци",
  "Карбинци",
  "Карпош",
  "Кисела Вода",
  "Кичево",
  "Конче",
  "Кочани",
  "Кратово",
  "Крива Паланка",
  "Кривогаштани",
  "Крушево",
  "Куманово",
  "Липково",
  "Лозово",
  "Маврово и Ростуша",
  "Македонска Каменица",
  "Македонски Брод",
  "Могила",
  "Неготино",
  "Новаци",
  "Ново Село",
  "Охрид",
  "Петровец",
  "Пехчево",
  "Пласница",
  "Прилеп",
  "Пробиштип",
  "Радовиш",
  "Ранковце",
  "Ресен",
  "Росоман",
  "Сарај",
  "Свети Николе",
  "Скопје",
  "Сопиште",
  "Старо Нагоричане",
  "Струга",
  "Струмица",
  "Студеничани",
  "Теарце",
  "Тетово",
  "Центар Жупа",
  "Чаир",
  "Чашка",
  "Чешиново",
  "Чучер Сандево",
  "Штип",
  "Центар",
  "Шуто Оризари",
];
export const manucipalities = [
  "Berovo",
  "Bitola",
  "Bogdanci",
  "Bogovinje",
  "Bosilovo",
  "Brvenica",
  "Debar",
  "Debarca",
  "Demir Hisar",
  "Demir Kapija",
  "Dolneni",
  "Gevgelija",
  "Gostivar",
  "Grad Skopje",
  "Gradsko",
  "Ilinden",
  "Jegunovce",
  "Karbinci",
  "Kavadarci",
  "Kratovo",
  "Kriva Palanka",
  "Kumanovo",
  "Lozovo",
  "Makedonska Kamenica",
  "Makedonski Brod",
  "Mogila",
  "Negotino",
  "Novaci",
  "Novo Selo",
  "Ohrid",
  "Arachinovo",
  "Centar Zhupa",
  "Delchevo",
  "Dojran",
  "Kichevo",
  "Konche",
  "Kochani",
  "Krivogashtani",
  "Krushevo",
  "Lipkovo",
  "Mavrovo and Rostuša",
  "Pehchevo",
  "Probishtip",
  "Radovish",
  "Rankovce",
  "Opština Sopište",
  "Staro Nagorichane",
  "Studenichani",
  "Vevchani",
  "Vrapchishte",
  "Chashka",
  "Chucher Sandevo",
  "Shtip",
  "Zhelino",
  "Petrovec",
  "Plasnica",
  "Prilep",
  "Resen",
  "Rosoman",
  "Struga",
  "Strumica",
  "Sveti Nikole",
  "Tearce",
  "Tetovo",
  "Valandovo",
  "Vasilevo",
  "Veles",
  "Vinica",
  "Zelenikovo",
  "Zrnovci",
  "Češinovo-Obleševo",
];

// export const manucipalities = [
//   { label: "Kumanovo", value: "kumanovo" },
//   { label: "Skopje", value: "skopje" },
// ];

export const populatedPlaces = ["Ajducka Cesma", "Tabanovce"];

export const districts = ["Oktomvriska", "Dragomance"];
// ------------------------------------------------------------
// ------------------------------------------------------------
