export const tagsMatcher = {
  "Балкон / Тераса": "balcony",
  Лифт: "elevator",
  "Паркинг простор / Гаража": "parking",
  "Нова градба": "new_building",
  Наместен: "furnished",
  Интерфон: "interfone",
  "Шпорет / Камин": "fireplace",
  Реновиран: "renovated",
  "Самостојна куќа": "detached_house",
  Подрум: "basement",
  Приземје: "ground_floor",
  Поткровје: "attic",
  Ново: "new",
  "Користено - Како Ново": "used_as_new",
  "Користено - Во добра состојба": "used_in_good_condition",
  "Користено - Во солидна состојба": "used_solid_condition",
};

// export const featureMatcher = {
//   balcony: 11,
//   elevator: 10,
//   parking: 9,
//   new_building: 2,
//   furnished: 33,
//   interfone: 3,
//   fireplace: 41,
//   renovated: "renovated",
//   detached_house: "detached_house",
//   basement: "basement",
//   ground_floor: "ground_floor",
//   attic: "attic",
//   new: "new",
//   used_as_new: "used_as_new",
//   used_in_good_condition: "used_in_good_condition",
//   used_solid_condition: "used_solid_condition",
// };

export const municipalityMatcher = {
  "Скопје, Скопjе": "10079",
  "Центар, Скопjе": "10079",
  "Кисела Вода, Скопjе": "10001",
  "Карпош, Скопjе": "10008",
  "Илинден, Скопjе": "10014",
  "Аеродром, Скопjе": "10002",
  "Ѓорче Петров, Скопjе": "10007",
};

export const placeMatcher = {
  "Avtokomanda -East Gate": "28001",
  Treska: "10079", // TODO: check if this is correct
  'Kisela Voda "CESHMA"': "20113",
  "KARPOS 4": "20808",
  "Centar pozadi Limak": "27906",
  "Madzir Maalo": "27910",
  Crnice: "20112",
  "Kiril i Metodij": "27906",
  "KARPOS 3 Ruski stan": "20807",
  "Stara Carsija": "27906",
  "CENTAR KAPISTEC": "27903",
  "Rugjer Boshkovikj": "20805",
  "Ул. Македонија": "27906",
  Центар: "27906",
  Kapistec: "27903",
  VLAE: "20708",
  "Kisela Voda": "20105",
  Centar: "27906",
  "Karpos 4 kaj Antiko": "20808",
  "N.Parapunov": "10079", //
  Kozle: "20809",
  "Orce Nikolov": "20805",
  "KAPISTEC D.Vodno": "27903",
  HROM: "20715",
  "Karpos 3": "20807",
  "CENTAR J.MIJALKOV": "27906",
  'Centar "Ramstore"': "27906",
  Ruzveltova: "20805",
  "GJORCE PETROV 3 DEKSION": "20706",
  "pozadi Katolicka Centar": "27906",
  "CENTAR ZOIL MAKEDONIJA": "27906",
  "naselba DRMA": "10079", //
  Univerzalna: "27906",
  Taftalidze: "20812",
  "gim. Josip Broz Tito": "27906",
  Vodno: "27904",
  "Taftalidze Vero 2": "20813",
  "Капиштец Загребска": "27903",
  Prashka: "20805",
  VODNO: "27904",
  "Sredno Nerezi": "20811",
  Leninova: "27906",
  Partizanska: "27901",
  "ul. Makedonija": "27906",
  "Bul. sv. Kliment Ohridski": "27906",
  'KOZLE "Kanela"': "20809",
  "11 Oktomvri": "20114",
  "Centar- Plostad Makedonija": "27906",
  "K.Voda ul. Puskinova": "20114",
  CRNICE: "20112",
  'Centar "Kras"': "27906",
  "KARPOS 3-TAFTALIDZE 1": "20807",
  "Gjorce Petrov": "20710",
  "Mlecen Taftalidze": "20812",
  "Limak Diamond": "27906",
  "Centar Grcka Amb.": "27906",
  "Dositej Obradovikj": "27906",
  "Debar Maalo": "27901",
  Vlae: "20708",
  "Nova Zeleznicka": "27906",
  "Madzari B. Stefkovski": "28001",
  "CENTAR-KATOLICKA UNIVERZALNA": "27906",
  "VELKO VLAHOVIK CENTAR REKORD": "27906",
  "Panorama Residence": "27907",
  "Kozle Germanska amb.": "20809",
  "vo Dzevair kulite-Aerodrom": "20203",
  "T.Aleksandrov": "27904",
  "Centar-Rekord": "27906",
  "Centar Crven Krst": "27906",
  "Flat Iron K.V. Rampa": "20105",
  "Taftalidze 1": "20812",
  "Taftalidze Mlecen Rest": "20812",
  Zdanec: "20803",
  "Crnice nad KAM": "20112",
  KOZLE: "20809",
  Bunjakovec: "27901",
  "Taftalidze 2": "20813",
  Bardovci: "20708",
  Stogovo: "20809",
  "Centar -Debar Maalo": "27901",
  "Centar Diamond-Limak": "27906",
  "selo Bardovci": "20708",
  "Vlae so Gjorce kaj Kruzniot tek": "20708",
  "Gradski Park Rezidens": "27906",
  "CENTAR -Ramstor Mall": "27906",
  "Vodno Kocho Racin": "27904",
  "Petar Deljan": "20105",
  "East Gate": "28001",
};

const typeMapping = {
  apartment: "Станови",
  house: "Куќи/Вили",
  vacation_house: "vacation_house",

  // Commercial types
  office: "Канцеларија",
  store: "Дуќани и Трафики",
  warehouse: "Магацин",
  industrial_space: "industrial_space",

  // Land types
  construction: "construction",
  agricultural: "agricultural",

  // Other types
  garage: "Бараки и Гаражи",
  business: "business",
  assembly_facilities: "assembly_facilities",
  other: "other",
};
const categoryMapping = {
  residential: ["apartment", "house", "vacation_house"],
  commercial: ["office", "store", "warehouse", "industrial_space"],
  land: ["construction", "agricultural"],
  other: ["garage", "business", "assembly_facilities", "other"],
};
export const typeMatcher = {
  stanovi: "apartment",
  kancelarija: "office",
  "kukji-vili": "house",
  magacin: "warehouse",
  "dukani-trafiki": "store",
  "baraki-garazi": "garage",
};
export const categoryMatcher = {
  stanovi: "residential",
  kancelarija: "commercial",
  "kukji-vili": "residential",
  magacin: "commercial",
  "dukani-trafiki": "commercial",
  "baraki-garazi": "other",
};
