import React from "react";
import {
  Section,
  Row,
  Column,
  Text,
  Link,
  Img,
  Container,
  Body,
  Html,
} from "@react-email/components";
import {
  Account,
  Listing,
  ListingStatus,
  LocationPrecision,
  PropertyCategory,
  PropertyTransactionType,
  PropertyType,
  SavedSearch,
  User,
} from "@prisma/client";
import { UploadedImageData } from "@/types/listing.types";
import { unpackSavedSearchParams } from "@/server/specific-utils/notifications.utils";
import { figureOutTags } from "@/server/specific-utils/listings.utils";
import { getMunicipalityPlacesTranslated } from "@/lib/data/macedonia/importantData";
import {
  camelCaseToNormal,
  displayDate,
  displayPrice,
  displayPriceMonthly,
} from "@/lib/utils";
const listingData = {
  id: 385,
  uuid: "0e69749a-516c-4bc4-b101-11bb421dc2d8",
  externalRef: "24906",
  listingNumber: "10385",
  createdAt: "2025-02-24 04:24:55.047",
  updatedAt: "2025-02-24 04:24:55.519",
  dateAvailable: "2025-02-24 04:24:55.047",
  isAvailable: true,
  userId: null,
  agencyId: "5",
  queryHash: "",
  transactionType: "sale",
  category: "residential",
  type: "house",
  municipality: "10001",
  place: "20102",
  address: "11 Oktomvri, Љубаш",
  fullAddress:
    "10001, 20114, 11 Oktomvri, Љубаш, Drachevo, Municipality of Kisela Voda, City of Skopje, 1050, North Macedonia",
  district: null,
  longitude: "21.497229",
  latitude: "41.928112",
  locationPrecision: "exact",
  enTitle: "",
  mkTitle: "Kuka vo naselba 11.Oktomvri",
  alTitle: "",
  enDescription: null,
  mkDescription: `sifra 24 906
Se prodava baraka + zidana dogradba vkupno stamben del 140m2 na parcela 279m2 vo Naselba 11. Oktomvri

cena 170.000e.
077 705 108
Agencija Doma Dom
info@domadom.mk
Опис на линк
Real estate DOMA DOM
Агенцијата за недвижности Real Estate DOMA DOM е доверлива агенција за недвижности во Скопје, Македонија, која е посветена на помагање на своите клиенти во наоѓање на совршениот дом или инвестициска можност. Со долгогодишно искуство во областа на недвижности, Агенцијата за недвижности DOMA DOM Ви нуди широк избор на недвижности - куќи, станови, викендички, и деловни простори, како и други имоти ширум Македонија.

Како агенција на која може да и верувате, Real Estate DOMA DOM поседува тим од професионалци кои се секогаш подготвени да Ви помогнат во секој чекор од процесот, било да сте во потрага по нов стан, куќа или имот за инвестиција. Секој клиент добива индивидуален пристап и целосна поддршка со цел постигнување на најдоброто возможно решение при купување, издавање или продажба на куќи и станови.

Понудата на недвижности вклучува различни типови на имоти во сите делови на Скопје и пошироко, така што без разлика дали барате нов дом или деловен простор, Real Estate DOMA DOM е тука за Вас. Преку Агенцијата за недвижности DOMA DOM, можете да ги пронајдете најдобрите недвижности кои ќе ги исполнат Вашите потреби и очекувања.

Доверете се на агенција со искуство, професионализм и квалитетна услуга во областа на недвижности. (stanovi vo Skopje, Centar, Karpos, Taftalidze)

Овластен агент за MoneyGram -money transfer,
Посети ја страната на нашата продавница
str.Mitropolit Teodosij Gologanov nb.72b lok.18 Прикажи на мапата
00389023051300
https://www.domadom.mk`,
  alDescription: null,
  price: "170000",
  previousPrice: null,
  priceHistory: null,
  area: "140",
  mainImage: {
    key: "RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    url: "https://utfs.io/f/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    name: "kuka-vo-naselba-11-oktomvri.jpeg",
    size: 5712,
    type: "image/jpeg",
    appUrl:
      "https://utfs.io/a/qn90x0r2nl/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    customId: null,
    fileHash: "4436bf8a6c26746bdd04b54e3c97f244",
    lastModified: 1740370982657,
  },
  images: [
    {
      key: "RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      url: "https://utfs.io/f/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      name: "kuka-vo-naselba-11-oktomvri.jpeg",
      size: 5712,
      type: "image/jpeg",
      appUrl:
        "https://utfs.io/a/qn90x0r2nl/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      customId: null,
      fileHash: "4436bf8a6c26746bdd04b54e3c97f244",
      lastModified: 1740370982657,
    },
  ],
  videoLink: null,
  status: "ACTIVE",
  isArchived: false,
  isPaidPromo: false,
  isPublished: true,
  publishedAt: "2025-02-24 04:24:55.039",
  publishEndDate: "2025-08-23 04:24:55.039",
  viewCountId: null,
  professionalPromotionId: null,
  substatus: "autogenerated",
};

const typedListingData: Listing = {
  ...listingData,
  id: listingData.id,
  listingNumber: parseInt(listingData.listingNumber),
  userId: listingData.userId,
  createdAt: new Date(listingData.createdAt),
  updatedAt: new Date(listingData.updatedAt),
  dateAvailable: new Date(listingData.dateAvailable),
  transactionType: listingData.transactionType as PropertyTransactionType,
  category: listingData.category as PropertyCategory,
  type: listingData.type as PropertyType,
  status: listingData.status as ListingStatus,
  longitude: parseFloat(listingData.longitude),
  latitude: parseFloat(listingData.latitude),
  locationPrecision: listingData.locationPrecision as LocationPrecision,
  price: parseInt(listingData.price),
  area: parseInt(listingData.area),
  mainImage: listingData.mainImage as UploadedImageData,
  images: listingData.images as UploadedImageData[],
  videoLink: listingData.videoLink as string | null,
  substatus: listingData.substatus || "",
  externalRef: listingData.externalRef || "",
  queryHash: listingData.queryHash || "",
  isArchived: listingData.isArchived || false,
  isPaidPromo: listingData.isPaidPromo || false,
  isPublished: listingData.isPublished as boolean,
  publishedAt: new Date(listingData.publishedAt),
  publishEndDate: new Date(listingData.publishEndDate),
  viewCountId: listingData.viewCountId as number | null,
  professionalPromotionId: listingData.professionalPromotionId as number | null,
  agencyId: parseInt(listingData.agencyId),
};
const savedSearchData: SavedSearch = {
  id: 23,
  userId: 23,
  name: "Nekogas",
  img: "/assets/region-map-preview.png",
  isNotificationOn: false,
  notificationInterval: "weekly",
  searchParams: "/search/tt-sale/l-10010/c-land/s-new",
  createdAt: new Date("2025-02-27 17:19:30.005"),
  updatedAt: new Date("2025-02-27 17:20:26.585"),
  lastOpenedAt: new Date("2025-02-27 17:19:30.005"),
};

const NewListingsThatMatchesNotification = ({
  listing = typedListingData,
  matchedSearches = [savedSearchData],
  user,
}: {
  listing: Listing;
  matchedSearches: SavedSearch[];
  user: Partial<User> & { account: Partial<Account> };
}) => {
  const { municipality, places } = getMunicipalityPlacesTranslated(
    listing?.municipality,
    "en",
  );

  const currentMunicipalityLabel = municipality?.label;
  const currentPlaceLabel = places?.find(
    (place) => place.value === listing?.place,
  )?.label;
  const fullAddress = `${currentMunicipalityLabel || ""}, ${currentPlaceLabel || ""}, ${listing?.address || ""}`;
  const isNew =
    listing.publishedAt &&
    listing.publishedAt.getTime() === listing.updatedAt.getTime();
  return (
    <Html>
      <Body
        style={{
          margin: 0,
          padding: 24,
          backgroundColor: "#f9f9f9",
          fontFamily: "Arial, sans-serif",
        }}
      >
        <Container
          style={{
            width: "100%",
            maxWidth: "600px",
            margin: "20px auto",
            backgroundColor: "#ffffff",
            padding: "20px",
            borderRadius: "8px",
            boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
          }}
        >
          <Section
            style={{ paddingBottom: "20px", borderBottom: "1px solid #ddd" }}
          >
            <Text
              style={{ fontSize: "16px", color: "#333", margin: "0 0 10px 0" }}
            >
              Dear {user.firstName} {user.lastName},
            </Text>
            <Text style={{ fontSize: "14px", color: "#666", margin: "0" }}>
              We&apos;re sending this notification because we found some
              exciting new listings that matches your saved searches.
            </Text>
          </Section>
        </Container>
        <Container
          style={{
            width: "100%",
            maxWidth: "600px",
            margin: "0 auto",
            backgroundColor: "#ffffff",
            padding: "20px",
            borderRadius: "8px",
            boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
          }}
        >
          {/* Header Section */}
          <Section style={{ textAlign: "center", paddingBottom: "20px" }}>
            <Text
              style={{
                margin: 0,
                color: "#333",
                fontSize: "24px",
                fontWeight: "bold",
              }}
            >
              New Listing Alert!
            </Text>
            <Text style={{ margin: 0, color: "#333", fontSize: "16px" }}>
              We found a property that matches your interests.
            </Text>
          </Section>
          {/* Listing Details Section */}
          <Section
            style={{
              padding: "10px 0",
              borderBottom: "1px solid #ddd",
              marginTop: "20px",
            }}
          >
            <Row>
              <Column width="30%" style={{ padding: 0 }}>
                <Img
                  src={(listing.mainImage as UploadedImageData)?.url ?? ""}
                  width="100%"
                  alt="Listing Image"
                  style={{ display: "block", objectFit: "contain" }}
                />
                <Section style={{ padding: "10px" }}>
                  <Row style={{ padding: "0 10px" }}>
                    {figureOutTags(listing).map((tag, index) => (
                      <Column
                        key={index}
                        style={{
                          paddingRight: "0px",
                          paddingBottom: "5px",
                          paddingLeft: "2px",
                        }}
                      >
                        <Text
                          style={{
                            fontSize: "12px",
                            color: "#555",
                            margin: "0",
                            display: "inline-block",
                          }}
                        >
                          <span
                            style={{
                              padding: "2px 4px",
                              borderRadius: "4px",
                              backgroundColor: "#f0f0f0",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {camelCaseToNormal(tag)}
                          </span>
                        </Text>
                      </Column>
                    ))}
                  </Row>
                </Section>
              </Column>
              <Column
                width="70%"
                style={{ padding: "20px", paddingTop: 0, verticalAlign: "top" }}
              >
                <Text
                  style={{
                    fontSize: "18px",
                    fontWeight: "600",
                    marginBottom: "5px",
                    marginTop: 0,
                  }}
                >
                  {listing.enTitle || listing.mkTitle || listing.alTitle}
                </Text>
                <Text
                  style={{
                    fontSize: "14px",
                    color: "#555",
                    marginBottom: "10px",
                  }}
                >
                  {fullAddress}
                </Text>
                <Row
                  style={{
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: "10px",
                    marginTop: 0,
                  }}
                >
                  <Column>
                    <Text
                      style={{ fontSize: "12px", color: "#555", margin: 0 }}
                    >
                      Posted on {displayDate(listing.publishedAt)}{" "}
                      <span
                        style={{
                          fontSize: "12px",
                          color: "blue",
                          fontWeight: "bold",
                          marginTop: 0,
                          marginBottom: 6,
                          display: "inline-block",
                          marginLeft: 6,
                          padding: "4px",
                          border: "1px solid blue",
                          borderRadius: "4px",
                        }}
                      >
                        {isNew ? "Ново" : "Ажурирано"}
                      </span>
                    </Text>
                  </Column>
                </Row>
                <Text
                  style={{
                    fontSize: "14px",
                    color: "#333",
                    marginBottom: "15px",
                    lineClamp: 2,
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: "vertical",
                    overflow: "hidden",
                    display: "block",
                    maxHeight: "3em",
                    lineHeight: "1.5em",
                    wordWrap: "break-word",
                  }}
                >
                  {listing.mkDescription ||
                    listing.enDescription ||
                    listing.alDescription}
                </Text>
                <Row style={{ marginBottom: "10px" }}>
                  <Column style={{ paddingRight: "10px" }}>
                    <Text
                      style={{
                        fontSize: "20px",
                        fontWeight: "bold",
                        margin: "0",
                      }}
                    >
                      {listing.transactionType === "sale"
                        ? displayPrice(listing.price)
                        : displayPriceMonthly(listing.price)}
                    </Text>
                  </Column>
                  {listing.previousPrice &&
                    listing.price &&
                    listing.previousPrice > listing.price && (
                      <Column style={{ paddingRight: "10px" }}>
                        <Text
                          style={{
                            fontSize: "16px",
                            color: "red",
                            textDecoration: "line-through",
                            margin: "0",
                          }}
                        >
                          {displayPrice(listing.previousPrice)}
                        </Text>
                      </Column>
                    )}
                  {listing.area && listing.price && (
                    <Column>
                      <Text style={{ fontSize: "14px", margin: "0" }}>
                        {displayPrice(listing.price / listing.area)} /m²
                      </Text>
                    </Column>
                  )}
                </Row>
              </Column>
            </Row>
            <Link
              href={`https://dev.adresa.mk/listing/${listing.id}`}
              style={{
                display: "block",
                width: "94%",
                margin: "0 auto",
                backgroundColor: "#0073e6",
                color: "#fff",
                textAlign: "center",
                padding: "12px",
                borderRadius: "5px",
                textDecoration: "none",
                marginTop: "20px",
              }}
            >
              View Listing
            </Link>
          </Section>

          {/* Search Criteria Section */}
          {matchedSearches.sort(
            (a, b) => b.createdAt.getTime() - a.createdAt.getTime(),
          ).length > 0 && (
            <Section
              style={{
                paddingTop: "20px",
                fontSize: "14px",
                color: "#333",
                borderTop: "1px solid #ddd",
              }}
            >
              <Text style={{ fontSize: "16px", color: "#333" }}>
                This listing matches your saved search criteria:
              </Text>
              {matchedSearches.map((search, index) => (
                <Row
                  key={index}
                  style={{
                    marginBottom: "10px",
                  }}
                >
                  <Column>
                    <Text style={{ fontSize: "12px", margin: "2px 0" }}>
                      <strong>Name:</strong> {search.name} |{" "}
                    </Text>
                    <Text style={{ fontSize: "12px", margin: "2px 0" }}>
                      <strong>Saved on:</strong>{" "}
                      {search.createdAt.toLocaleDateString()}
                    </Text>
                    {/* Unpacked search params */}

                    {Object.entries(
                      unpackSavedSearchParams(search.searchParams),
                    ).map(([key, value]) => (
                      <Text style={{ fontSize: "12px", margin: "2px 0" }}>
                        <strong>{camelCaseToNormal(key)}:</strong>{" "}
                        {Array.isArray(value) ? value.join(", ") : value}
                      </Text>
                    ))}
                    <Text style={{ fontSize: "12px", margin: "2px 0" }}>
                      <Link
                        href={`https://dev.adresa.mk${search.searchParams}`}
                        style={{ color: "#0073e6" }}
                      >
                        Search listings for this criteria
                      </Link>
                    </Text>
                  </Column>
                </Row>
              ))}
            </Section>
          )}

          {/* Footer Section */}
          <Section
            style={{
              textAlign: "center",
              paddingTop: "20px",
              fontSize: "12px",
              color: "#aaa",
            }}
          >
            <Text>
              If you no longer wish to receive these emails, you can{" "}
              <Link href="unsubscribe_url" style={{ color: "#0073e6" }}>
                unsubscribe here
              </Link>
              .
            </Text>
            <Text>© 2025 Adresa.mk. All rights reserved.</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default NewListingsThatMatchesNotification;
