import React from "react";
import {
  Section,
  Row,
  Column,
  Text,
  Link,
  Img,
  Container,
  Body,
  Html,
} from "@react-email/components";
import {
  Listing,
  ListingStatus,
  LocationPrecision,
  PropertyCategory,
  PropertyTransactionType,
  PropertyType,
  SavedSearch,
} from "@prisma/client";
import { UploadedImageData } from "@/types/listing.types";
const listingData = {
  id: 385,
  uuid: "0e69749a-516c-4bc4-b101-11bb421dc2d8",
  externalRef: "24906",
  listingNumber: "10385",
  createdAt: "2025-02-24 04:24:55.047",
  updatedAt: "2025-02-24 04:24:55.519",
  dateAvailable: "2025-02-24 04:24:55.047",
  isAvailable: true,
  userId: null,
  agencyId: "5",
  queryHash: "",
  transactionType: "sale",
  category: "residential",
  type: "house",
  municipality: "10001",
  place: "20102",
  address: "11 Oktomvri, Љубаш",
  fullAddress:
    "10001, 20114, 11 Oktomvri, Љубаш, Drachevo, Municipality of Kisela Voda, City of Skopje, 1050, North Macedonia",
  district: null,
  longitude: "21.497229",
  latitude: "41.928112",
  locationPrecision: "exact",
  enTitle: "",
  mkTitle: "Kuka vo naselba 11.Oktomvri",
  alTitle: "",
  enDescription: null,
  mkDescription: `sifra 24 906
Se prodava baraka + zidana dogradba vkupno stamben del 140m2 na parcela 279m2 vo Naselba 11. Oktomvri

cena 170.000e.
077 705 108
Agencija Doma Dom
info@domadom.mk
Опис на линк
Real estate DOMA DOM
Агенцијата за недвижности Real Estate DOMA DOM е доверлива агенција за недвижности во Скопје, Македонија, која е посветена на помагање на своите клиенти во наоѓање на совршениот дом или инвестициска можност. Со долгогодишно искуство во областа на недвижности, Агенцијата за недвижности DOMA DOM Ви нуди широк избор на недвижности - куќи, станови, викендички, и деловни простори, како и други имоти ширум Македонија.

Како агенција на која може да и верувате, Real Estate DOMA DOM поседува тим од професионалци кои се секогаш подготвени да Ви помогнат во секој чекор од процесот, било да сте во потрага по нов стан, куќа или имот за инвестиција. Секој клиент добива индивидуален пристап и целосна поддршка со цел постигнување на најдоброто возможно решение при купување, издавање или продажба на куќи и станови.

Понудата на недвижности вклучува различни типови на имоти во сите делови на Скопје и пошироко, така што без разлика дали барате нов дом или деловен простор, Real Estate DOMA DOM е тука за Вас. Преку Агенцијата за недвижности DOMA DOM, можете да ги пронајдете најдобрите недвижности кои ќе ги исполнат Вашите потреби и очекувања.

Доверете се на агенција со искуство, професионализм и квалитетна услуга во областа на недвижности. (stanovi vo Skopje, Centar, Karpos, Taftalidze)

Овластен агент за MoneyGram -money transfer,
Посети ја страната на нашата продавница
str.Mitropolit Teodosij Gologanov nb.72b lok.18 Прикажи на мапата
00389023051300
https://www.domadom.mk`,
  alDescription: null,
  price: "170000",
  previousPrice: null,
  priceHistory: null,
  area: "140",
  mainImage: {
    key: "RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    url: "https://utfs.io/f/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    name: "kuka-vo-naselba-11-oktomvri.jpeg",
    size: 5712,
    type: "image/jpeg",
    appUrl:
      "https://utfs.io/a/qn90x0r2nl/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
    customId: null,
    fileHash: "4436bf8a6c26746bdd04b54e3c97f244",
    lastModified: 1740370982657,
  },
  images: [
    {
      key: "RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      url: "https://utfs.io/f/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      name: "kuka-vo-naselba-11-oktomvri.jpeg",
      size: 5712,
      type: "image/jpeg",
      appUrl:
        "https://utfs.io/a/qn90x0r2nl/RCUZyUk9Cyhb8JbJW4ErkbtnsfcpNgaLOdSDo4xTvPhM3UHW",
      customId: null,
      fileHash: "4436bf8a6c26746bdd04b54e3c97f244",
      lastModified: 1740370982657,
    },
  ],
  videoLink: null,
  status: "ACTIVE",
  isArchived: false,
  isPaidPromo: false,
  isPublished: true,
  publishedAt: "2025-02-24 04:24:55.039",
  publishEndDate: "2025-08-23 04:24:55.039",
  viewCountId: null,
  professionalPromotionId: null,
  substatus: "autogenerated",
};

const typedListingData: Listing = {
  ...listingData,
  id: listingData.id,
  listingNumber: parseInt(listingData.listingNumber),
  userId: listingData.userId,
  createdAt: new Date(listingData.createdAt),
  updatedAt: new Date(listingData.updatedAt),
  dateAvailable: new Date(listingData.dateAvailable),
  transactionType: listingData.transactionType as PropertyTransactionType,
  category: listingData.category as PropertyCategory,
  type: listingData.type as PropertyType,
  status: listingData.status as ListingStatus,
  longitude: parseFloat(listingData.longitude),
  latitude: parseFloat(listingData.latitude),
  locationPrecision: listingData.locationPrecision as LocationPrecision,
  price: parseInt(listingData.price),
  area: parseInt(listingData.area),
  mainImage: listingData.mainImage as UploadedImageData,
  images: listingData.images as UploadedImageData[],
  videoLink: listingData.videoLink as string | null,
  substatus: listingData.substatus || "",
  externalRef: listingData.externalRef || "",
  queryHash: listingData.queryHash || "",
  isArchived: listingData.isArchived || false,
  isPaidPromo: listingData.isPaidPromo || false,
  isPublished: listingData.isPublished as boolean,
  publishedAt: new Date(listingData.publishedAt),
  publishEndDate: new Date(listingData.publishEndDate),
  viewCountId: listingData.viewCountId as number | null,
  professionalPromotionId: listingData.professionalPromotionId as number | null,
  agencyId: parseInt(listingData.agencyId),
};
const savedSearchData: SavedSearch = {
  id: 23,
  userId: 23,
  name: "Nekogas",
  img: "/assets/region-map-preview.png",
  isNotificationOn: false,
  notificationInterval: "weekly",
  searchParams: "/search/tt-sale/l-10010/c-land/s-new",
  createdAt: new Date("2025-02-27 17:19:30.005"),
  updatedAt: new Date("2025-02-27 17:20:26.585"),
  lastOpenedAt: new Date("2025-02-27 17:19:30.005"),
};

const NewListingsThatMatchesNotification = ({
  listing = typedListingData,
  matchedSearches = [savedSearchData],
}: {
  listing: Listing;
  matchedSearches: SavedSearch[];
}) => {
  return (
    <Html>
      <Body
        style={{
          margin: 0,
          padding: 0,
          backgroundColor: "#f9f9f9",
          fontFamily: "Arial, sans-serif",
        }}
      >
        <Container
          style={{
            width: "100%",
            maxWidth: "600px",
            margin: "0 auto",
            backgroundColor: "#ffffff",
            padding: "20px",
            borderRadius: "8px",
            boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
          }}
        >
          {/* Header Section */}
          <Section style={{ textAlign: "center", paddingBottom: "20px" }}>
            <Text
              style={{
                margin: 0,
                color: "#333",
                fontSize: "24px",
                fontWeight: "bold",
              }}
            >
              New Listing Alert!
            </Text>
            <Text style={{ margin: 0, color: "#333", fontSize: "16px" }}>
              We found a property that matches your interests.
            </Text>
          </Section>

          {/* Listing Details Section */}
          <Section
            style={{
              padding: "10px 0",
              borderTop: "1px solid #ddd",
              marginTop: "20px",
            }}
          >
            <Text
              style={{
                fontSize: "18px",
                fontWeight: "bold",
                marginBottom: "10px",
              }}
            >
              {listing.mkTitle || listing.enTitle || "Listing Title"}
            </Text>
            <Text style={{ fontSize: "14px", margin: "5px 0" }}>
              <strong>Location:</strong> {listing.fullAddress}
            </Text>
            <Text style={{ fontSize: "14px", margin: "5px 0" }}>
              <strong>Price:</strong> ${listing.price}
            </Text>
            <Text style={{ fontSize: "14px", margin: "5px 0" }}>
              <strong>Description:</strong> {listing.mkDescription}
            </Text>
            <Link
              href={`https://dev.adresa.mk/listing/${listing.id}`}
              style={{
                display: "block",
                width: "100%",
                backgroundColor: "#0073e6",
                color: "#fff",
                textAlign: "center",
                padding: "12px",
                borderRadius: "5px",
                textDecoration: "none",
                marginTop: "20px",
              }}
            >
              View Listing
            </Link>
          </Section>

          {/* Property Images */}
          <Section style={{ paddingTop: "20px" }}>
            {Array.isArray(listing.images) && listing.images.length > 0 && (
              <Row>
                {listing.images.slice(0, 3).map((image: any, index) => (
                  <Column key={index} style={{ width: "33%" }}>
                    <Img
                      src={image.url}
                      alt={`Listing Image ${index + 1}`}
                      width="100%"
                      style={{
                        borderRadius: "5px",
                        marginBottom: "10px",
                      }}
                    />
                  </Column>
                ))}
              </Row>
            )}
          </Section>

          {/* Search Criteria Section */}
          {matchedSearches.length > 0 && (
            <Section
              style={{
                paddingTop: "20px",
                fontSize: "14px",
                color: "#333",
                borderTop: "1px solid #ddd",
              }}
            >
              <Text style={{ fontSize: "14px", color: "#333" }}>
                This listing matches your saved search criteria:
              </Text>
              {matchedSearches.map((search, index) => (
                <Row key={index} style={{ marginBottom: "10px" }}>
                  <Column>
                    <Text style={{ fontSize: "14px", margin: "5px 0" }}>
                      <strong>Name:</strong> {search.name} |{" "}
                      <strong>Saved on:</strong>{" "}
                      {search.createdAt.toLocaleDateString()}
                    </Text>
                    <Text style={{ fontSize: "14px", margin: "5px 0" }}>
                      <Link
                        href={`https://dev.adresa.mk/${search.searchParams}`}
                        style={{ color: "#0073e6" }}
                      >
                        View More Listings
                      </Link>
                    </Text>
                  </Column>
                </Row>
              ))}
            </Section>
          )}

          {/* Footer Section */}
          <Section
            style={{
              textAlign: "center",
              paddingTop: "20px",
              fontSize: "12px",
              color: "#aaa",
            }}
          >
            <Text>
              If you no longer wish to receive these emails, you can{" "}
              <Link href="unsubscribe_url" style={{ color: "#0073e6" }}>
                unsubscribe here
              </Link>
              .
            </Text>
            <Text>© 2025 Your Company. All rights reserved.</Text>
          </Section>
        </Container>

        <Container
          style={{
            width: "325px",
            margin: "20px auto",
            backgroundColor: "white",
            borderRadius: "8px",
            boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
          }}
        >
          <Section style={{ position: "relative", padding: "0" }}>
            <Img
              src={(typedListingData.mainImage as UploadedImageData)?.url ?? ""}
              width="323"
              height="194"
              alt=""
              style={{
                display: "block",
                borderRadius: "8px 8px 0 0",
                objectFit: "cover",
              }}
            />
          </Section>
          <Section
            style={{ padding: "8px 16px", borderBottom: "1px solid #eee" }}
          >
            <Text style={{ fontSize: "16px", fontWeight: "600" }}>
              {typedListingData.mkTitle}
            </Text>
            <Text
              style={{
                fontSize: "14px",
                textTransform: "capitalize",
                marginTop: "4px",
              }}
            >
              {typedListingData.address}
            </Text>
          </Section>
          <Section
            style={{
              padding: "12px 16px",
              display: "flex",
              justifyContent: "space-around",
              alignItems: "center",
            }}
          >
            <Text style={{ fontSize: "18px", fontWeight: "600" }}>
              {typedListingData.price}
            </Text>
            {typedListingData.previousPrice &&
              typedListingData.price &&
              typedListingData.previousPrice > typedListingData.price && (
                <Text
                  style={{
                    marginLeft: "10px",
                    fontSize: "12px",
                    color: "#777",
                    textDecoration: "line-through",
                    display: "flex",
                    alignItems: "center",
                  }}
                >
                  <Text
                    style={{
                      color: "green",
                      fontSize: "16px",
                      marginRight: "4px",
                    }}
                  >
                    ↓
                  </Text>
                  {typedListingData.previousPrice}
                </Text>
              )}
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default NewListingsThatMatchesNotification;
